version: '3'

services:
  server:
    image: drone/drone:2
    restart: always
    environment:
      DRONE_SERVER_HOST: ${SERVER_HOST}:${SERVER_PORT}
      DRONE_SERVER_PROTO: http
      DRONE_GITEA_SERVER: ${DRONE_GITEA_SERVER}
      DRONE_GITEA_CLIENT_ID: ${DRONE_GITEA_CLIENT_ID}
      DRONE_GITEA_CLIENT_SECRET: ${DRONE_GITEA_CLIENT_SECRET}
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_USER_CREATE: ${DRONE_USER_CREATE}
    ports:
      - "${SERVER_PORT}:80"
    volumes:
      - /var/lib/drone:/data

  runner:
    image: drone/drone-runner-docker:1
    restart: always
    environment:
      DRONE_RPC_PROTO: http
      DRONE_RPC_HOST: server
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_RUNNER_CAPACITY: 2
      DRONE_RUNNER_NAME: my-docker-runner
    ports:
      - "${RUNNER_PORT}:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
